import '@rmp/ui/styles/base.css'

import { Metadata } from 'next'
import Link from 'next/link'

import { monoFont, sansFont } from '@rmp/ui/typography'
import { AppBar, Logo } from '@rmp/ui'

import { DrawerProvider, NavMenu } from 'components/navbar'

export const metadata: Metadata = {
  title: {
    absolute: 'LucasRMP',
    template: '%s | LucasRMP',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${monoFont.variable} ${sansFont.variable} text-slate-50`}
      data-theme="dark"
    >
      <body className="bg-base-100">
        <DrawerProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </DrawerProvider>
      </body>
    </html>
  )
}

const Header = () => {
  return (
    <AppBar>
      <Link href="/">
        <Logo />
      </Link>

      <NavMenu />
    </AppBar>
  )
}

const Footer = () => {
  return (
    <footer className="bg-neutral">
      <div className="wrapper p-4 text-slate-300 text-xl">© Chesp Design</div>
    </footer>
  )
}
