import 'styles/globals.css'
import { Metadata } from 'next'
import Link from 'next/link'

import { monoFont, sansFont } from '@rmp/ui/typography'
import { Button } from '@rmp/ui'

import { Logo } from 'components/svg/logo'

export const metadata: Metadata = {
  title: {
    absolute: 'LucasRMP',
    template: '%s | LucasRMP',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${monoFont.variable} ${sansFont.variable} text-slate-50`}
    >
      <body className="bg-slate-900 flex flex-col min-h-screen">
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  )
}

const Header = () => {
  return (
    <header className="flex items-center justify-between wrapper p-10">
      <Logo />

      <Button
        variant="outlined"
        size="sm"
        component={Link}
        href="https://www.buymeacoffee.com/lucasrmp"
        target="_blank"
      >
        <span className="text-slate-50 text-xl">Buy me a Coffee</span>
      </Button>
    </header>
  )
}

const Footer = () => {
  return (
    <footer className="bg-gray-900">
      <div className="wrapper p-4 text-slate-300 text-xl">© Chesp Design</div>
    </footer>
  )
}
